flowchart LR
    n1["GENERAL"] --> n2["G1"]
    n2 -- Si la respuesta es positiva --> n3["G3"]
    n2 -- Si la respuesta es negativa --> n4["G4"]
    n4 -- Si responde con el nombre de alguna de estas ciudades: atenas --> n5["Enviamos los mensajes de invitación de la ciudad correspondiente"]
    n3 -- Si la respuesta es positiva --> n6["G35"]
    n3 -- Si la respuesta es negativa --> n7["G7"]
    n6 -- Si la respuesta es liberia --> n8["G11"]
    n6 -- Si la respuesta no es liberia --> n9["G12"]
    n9 -- Si la respuesta es carro, automovil o B1 --> n10["G25"]
    n9 -- Si la respuesta es moto, A1, A2 o A3 --> n11["G28"]
    n9 -- Si la respuesta es B2 --> n12["G29"]
    n9 -- Si la respuesta es B3 --> n13["G30"]
    n9 -- Si la respuesta es B4 o Triller --> n14["G31"]
    n9 -- Si la respeusta es bus o C2 --> n15["G32"]
    n8 -- Si la respuesta es carro, automovil o B1 --> n16["G13"]
    n8 -- Si la respuesta es moto, A1, A2 o A3 --> n17["G16"]
    n8 -- Si la respuesta es B2 --> n18["G19"]
    n8 -- Si la respuesta es B3 --> n19["G20"]
    n8 -- Si la respeusta es B4 o Triller --> n20["G21"]
    n8 -- Si la respeusta es Bus o C2 --> n21["G22"]
    n22["Alquiler"] --> n23["A1"]
    n23 -- Si la respuesta es positiva --> n6
    n23 -- Si la respuesta es negativa --> n7
    n24["QUEJA"] --> n25["Q1"]
    n26["WIN"] --> n27["W1"]
    n28["DICTAMEN"] --Si no esta dentro de los resgistro--> n29["A1"]
    n28 --Si el id del cliente ya esta dentro de los registro-->n30["A1_1"]
    n31["CLASES"] -->n32["C1"]
    n32 -- Si la clase de manejo es en liberia --> n33["C2"]
    n32 -- Si la respuesta es negativa o indica que es en una sede diferente a Liberia --> n34["C5"]
